name: CI/CD Task Kangaroo Health

on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: 'Browser name'
        default: 'chrome'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Kill any running Chrome instances
        run: pkill -f "chrome" || true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable jq unzip
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | \
                       jq -r --arg ver "$CHROME_VERSION" '.channels.Stable | select(.version | startswith($ver)) | .downloads.chromedriver[] | select(.platform == "linux64") | .url')
          if [ -z "$DRIVER_URL" ]; then
            echo "Falling back to latest stable ChromeDriver"
            DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | \
                         jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          fi
          wget -O chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          google-chrome --version
          chromedriver --version

      - name: Run Cucumber TestRunner
        run: |
          mvn clean test \
            -Dbrowser=${{ inputs.browsername }} \
            -DenableBrowserOptions=true \
            -Dmaven.test.failure.ignore=true

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: ./reports/ExtentReport.html

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: ./reports/screenshots/